insert into registry.assets (symbol,name,category,decimals,mint,is_stable,is_lst,is_xstock,is_rwa,risk_tier,max_pot_weight_bps,supports_lp,supports_lending)
values
('SOL','Solana (Wrapped)','sol_lst',9,'So11111111111111111111111111111111111111112',false,false,false,false,2,10000,true,false),
('JitoSOL','Jito Staked SOL','sol_lst',9,'J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn',false,true,false,false,2,2500,true,false),
('mSOL','Marinade Staked SOL','sol_lst',9,'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',false,true,false,false,2,2500,true,false),
('bSOL','BlazeStake Staked SOL','sol_lst',9,'bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HJseex87',false,true,false,false,2,2500,false,false),
('INF','Sanctum Infinity','sol_lst',9,'5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm',false,true,false,false,2,2500,false,false),
('hSOL','Helius Staked SOL','sol_lst',9,null,false,true,false,false,3,2500,false,false),
('jupSOL','Jupiter Staked SOL','sol_lst',9,null,false,true,false,false,2,2500,false,false),
('bonkSOL','BonkSOL','sol_lst',9,null,false,true,false,false,3,2500,false,false),
('cgntSOL','Cogent SOL','sol_lst',9,null,false,true,false,false,3,2500,false,false),
('dSOL','Drift Staked SOL','sol_lst',9,null,false,true,false,false,3,2500,false,false),
('USDC','USD Coin','stablecoin',6,'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',true,false,false,false,1,2500,true,true),
('USDT','Tether USD','stablecoin',6,'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',true,false,false,false,1,2500,true,false),
('PYUSD','PayPal USD','stablecoin',6,'2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo',true,false,false,false,2,2500,false,false),
('USDS','Sky USDS','stablecoin',6,null,true,false,false,false,2,2500,false,false),
('USDe','Ethena USDe','stablecoin',6,null,true,false,false,false,3,2500,false,false),
('EURC','Euro Coin','stablecoin',6,null,true,false,false,false,2,2500,false,false),
('USDY','Ondo US Dollar Yield','stablecoin',6,null,true,false,false,true,3,2500,false,false),
('USDG','Global Dollar','stablecoin',6,null,true,false,false,false,2,2500,false,false),
('FDUSD','First Digital USD','stablecoin',6,null,true,false,false,false,3,2500,false,false),
('AUSD','Agora USD','stablecoin',6,null,true,false,false,false,3,2500,false,false),
('AAPLx','Apple xStock','xstock',8,null,false,false,true,false,4,2500,false,false),
('TSLAx','Tesla xStock','xstock',8,null,false,false,true,false,4,2500,false,false),
('NVDAx','NVIDIA xStock','xstock',8,null,false,false,true,false,4,2500,false,false),
('MSFTx','Microsoft xStock','xstock',8,null,false,false,true,false,4,2500,false,false),
('AMZNx','Amazon xStock','xstock',8,null,false,false,true,false,4,2500,false,false),
('GOOGLx','Alphabet xStock','xstock',8,null,false,false,true,false,4,2500,false,false),
('METAx','Meta xStock','xstock',8,null,false,false,true,false,4,2500,false,false),
('SPYx','S&P 500 xStock','xstock',8,null,false,false,true,false,3,2500,false,false),
('COINx','Coinbase xStock','xstock',8,null,false,false,true,false,4,2500,false,false),
('MSTRx','MicroStrategy xStock','xstock',8,null,false,false,true,false,5,2500,false,false),
('WBTC','Wrapped BTC (Wormhole)','blue_chip',8,null,false,false,false,false,2,2500,true,false),
('WETH','Wrapped ETH (Wormhole)','blue_chip',8,null,false,false,false,false,2,2500,true,false),
('cbBTC','Coinbase Wrapped BTC','blue_chip',8,null,false,false,false,false,2,2500,false,false),
('JUP','Jupiter','blue_chip',6,'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',false,false,false,false,3,2500,true,false),
('JTO','Jito','blue_chip',9,'jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL',false,false,false,false,3,2500,false,false),
('PYTH','Pyth Network','blue_chip',6,'HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3',false,false,false,false,3,2500,false,false),
('W','Wormhole','blue_chip',6,'85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ',false,false,false,false,3,2500,false,false),
('RAY','Raydium','blue_chip',6,'4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',false,false,false,false,3,2500,true,false),
('ORCA','Orca','blue_chip',6,'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',false,false,false,false,3,2500,false,false),
('TNSR','Tensor','blue_chip',9,'TNSRxcUxoT9xBG3de7PiJyTDYu7kskLqcpddxnEJAS6',false,false,false,false,4,2500,false,false),
('KMNO','Kamino','defi',6,'KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS',false,false,false,false,4,2500,false,false),
('DRIFT','Drift Protocol','defi',6,'DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7',false,false,false,false,4,2500,false,false),
('MNDE','Marinade','defi',9,'MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey',false,false,false,false,4,2500,false,false),
('MeteoraMET','Meteora','defi',6,null,false,false,false,false,4,2500,false,false),
('CLOUD','Cloud (Sanctum)','defi',9,null,false,false,false,false,4,2500,false,false),
('PRCL','Parcl','defi',6,null,false,false,false,true,4,2500,false,false),
('LFNTY','Lifinity','defi',6,null,false,false,false,false,4,2500,false,false),
('SLND','Solend / Save','defi',6,null,false,false,false,false,4,2500,false,false),
('MRLN','Marlin','defi',6,null,false,false,false,false,5,2500,false,false),
('FXS','Frax Share (Sol)','defi',6,null,false,false,false,false,4,2500,false,false),
('PHANTOM','Phantom (placeholder)','defi',6,null,false,false,false,false,5,2500,false,false),
('ZEUS','Zeus Network','defi',6,null,false,false,false,false,5,2500,false,false),
('RENDER','Render','ai',8,'rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof',false,false,false,false,4,2500,false,false),
('AI16Z','ai16z','ai',9,null,false,false,false,false,5,2500,false,false),
('GRIFFAIN','Griffain','ai',6,null,false,false,false,false,5,2500,false,false),
('ARC','AI Rig Complex','ai',6,null,false,false,false,false,5,2500,false,false),
('FARTCOIN','Fartcoin','ai',6,null,false,false,false,false,5,2500,false,false),
('ZEREBRO','Zerebro','ai',6,null,false,false,false,false,5,2500,false,false),
('GOAT','Goatseus Maximus','ai',6,null,false,false,false,false,5,2500,false,false),
('TANK','AgentTank','ai',6,null,false,false,false,false,5,2500,false,false),
('NEUR','Neur','ai',6,null,false,false,false,false,5,2500,false,false),
('SWARMS','Swarms','ai',6,null,false,false,false,false,5,2500,false,false),
('HNT','Helium','infrastructure',8,'hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux',false,false,false,false,3,2500,false,false),
('MOBILE','Helium Mobile','infrastructure',6,null,false,false,false,false,4,2500,false,false),
('IOT','Helium IOT','infrastructure',6,null,false,false,false,false,4,2500,false,false),
('RENDER2','Render (legacy RNDR)','infrastructure',8,null,false,false,false,false,4,2500,false,false),
('SHDW','GenesysGo Shadow','infrastructure',9,null,false,false,false,false,4,2500,false,false),
('NOS','Nosana','infrastructure',6,null,false,false,false,false,4,2500,false,false),
('GRASS','Grass','infrastructure',9,null,false,false,false,false,4,2500,false,false),
('PIPE','Pipe Network','infrastructure',6,null,false,false,false,false,5,2500,false,false),
('IO','io.net','infrastructure',8,null,false,false,false,false,4,2500,false,false),
('DBR','deBridge','infrastructure',6,null,false,false,false,false,4,2500,false,false),
('BONK','Bonk','meme',5,'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',false,false,false,false,5,2500,true,false),
('WIF','dogwifhat','meme',6,'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm',false,false,false,false,5,2500,false,false),
('POPCAT','Popcat','meme',9,null,false,false,false,false,5,2500,false,false),
('MEW','cat in a dogs world','meme',5,null,false,false,false,false,5,2500,false,false),
('PENGU','Pudgy Penguins','meme',6,null,false,false,false,false,5,2500,false,false),
('BOME','BOOK OF MEME','meme',6,null,false,false,false,false,5,2500,false,false),
('TRUMP','OFFICIAL TRUMP','meme',6,null,false,false,false,false,5,2500,false,false),
('MELANIA','Melania Meme','meme',6,null,false,false,false,false,5,2500,false,false),
('PNUT','Peanut the Squirrel','meme',6,null,false,false,false,false,5,2500,false,false),
('MOODENG','Moo Deng','meme',6,null,false,false,false,false,5,2500,false,false),
('ONDO','Ondo (bridged)','rwa',6,null,false,false,false,true,4,2500,false,false),
('OUSG','Ondo Short-Term US Gov','rwa',6,null,false,false,false,true,3,2500,false,false),
('BUIDL','BlackRock BUIDL (Sol)','rwa',6,null,false,false,false,true,3,2500,false,false),
('CETES','Mexican CETES (Etherfuse)','rwa',6,null,false,false,false,true,3,2500,false,false),
('TBILL','OpenEden T-Bill','rwa',6,null,false,false,false,true,3,2500,false,false),
('GOLD','Tokenized Gold (placeholder)','rwa',8,null,false,false,false,true,4,2500,false,false),
('PARCLR','Parcl Real Estate (placeholder)','rwa',6,null,false,false,false,true,4,2500,false,false),
('HOMES','Homebase RWA (placeholder)','rwa',6,null,false,false,false,true,5,2500,false,false),
('JLP','Jupiter Perps LP','yield',6,'27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4',false,false,false,false,3,2500,false,false),
('kSOL','Kamino SOL Vault','yield',9,null,false,false,false,false,4,2500,false,false),
('kUSDC','Kamino USDC Vault','yield',6,null,false,false,false,false,3,2500,false,false),
('sUSDe','Ethena Staked USDe','yield',6,null,false,false,false,false,4,2500,false,false),
('meSOL','Meteora SOL LST','yield',9,null,false,false,false,false,4,2500,false,false),
('lstSOL','Generic LST yield','yield',9,null,false,false,false,false,4,2500,false,false),
('vSOL','The Vault SOL','yield',9,null,false,false,false,false,4,2500,false,false),
('picoSOL','picoSOL','yield',9,null,false,false,false,false,4,2500,false,false),
('compoundUSDC','Compounding USDC (placeholder)','yield',6,null,false,false,false,false,4,2500,false,false),
('driftUSDC','Drift USDC Earn','yield',6,null,false,false,false,false,4,2500,false,false)
on conflict (mint) do nothing;
