import { AnchorProvider, Program, setProvider, BN } from '@coral-xyz/anchor'
import {
  Connection, PublicKey, Commitment, LAMPORTS_PER_SOL,
  SystemProgram, Transaction,
} from '@solana/web3.js'
import { POT_PROGRAM_ID } from './pda'
import type { PotState, MemberState, ProposalState, PotDisplay, MemberDisplay } from './types'

export interface PotSDKConfig {
  rpcUrl: string
  commitment?: Commitment
  programId?: PublicKey
}

export function createConnection(rpcUrl: string, commitment: Commitment = 'confirmed') {
  return new Connection(rpcUrl, commitment)
}

/**
 * Returns an Anchor Program instance for the POT vault.
 * IDL is auto-generated by `anchor build`
 */
export function getPotProgram(provider: AnchorProvider, idl: any) {
  setProvider(provider)
  return new Program(idl as any, provider)
}

// ── Basic POT helpers ─────────────────────────────────────────────────────────

/**
 * Fetch all POT accounts from the program
 */
export async function fetchAllPots(connection: Connection, programId = POT_PROGRAM_ID) {
  const accounts = await connection.getProgramAccounts(programId, {
    filters: [
      { dataSize: 8 + 500 }, // Approximate PotAccount size — adjust after IDL build
    ],
  })
  return accounts
}

/**
 * Fetch all POTs a wallet belongs to (via member PDAs)
 */
export async function fetchUserPots(
  connection: Connection,
  wallet: PublicKey,
  programId = POT_PROGRAM_ID
) {
  const accounts = await connection.getProgramAccounts(programId, {
    filters: [
      { memcmp: { offset: 8, bytes: wallet.toBase58() } },
    ],
  })
  return accounts
}

/**
 * Convert on-chain PotState + vault balance to display-friendly format
 */
export function potToDisplay(pubkey: PublicKey, pot: PotState, vaultBalance: number): PotDisplay {
  const TAMA_EMOJIS = ['🥚', '🐣', '🐤', '🦅', '🐉', '👑']
  const strategyKey = Object.keys(pot.config.yieldStrategy)[0]

  return {
    pubkey: pubkey.toBase58(),
    name: pot.name,
    emoji: pot.emoji || '🫙',
    balance: vaultBalance / LAMPORTS_PER_SOL,
    totalShares: pot.totalShares.toNumber(),
    memberCount: pot.memberCount,
    tradeCount: pot.tradeCount,
    tamagotchiLevel: pot.tamagotchiLevel,
    tamagotchiEmoji: TAMA_EMOJIS[pot.tamagotchiLevel] || '🥚',
    yieldStrategy: strategyKey,
    governanceLevel: pot.governance.tradeLevel,
    isPublic: pot.config.isPublic,
    createdAt: new Date(pot.createdAt.toNumber() * 1000),
  }
}

/**
 * Convert on-chain MemberState to display-friendly format
 */
export function memberToDisplay(member: MemberState, totalShares: number): MemberDisplay {
  const shares = member.shares.toNumber()
  return {
    wallet: member.wallet.toBase58(),
    shares,
    sharePercent: totalShares > 0 ? (shares / totalShares) * 100 : 0,
    depositTotal: member.depositTotal.toNumber() / LAMPORTS_PER_SOL,
    withdrawTotal: member.withdrawTotal.toNumber() / LAMPORTS_PER_SOL,
    pnl: (member.withdrawTotal.toNumber() - member.depositTotal.toNumber()) / LAMPORTS_PER_SOL,
    joinedAt: new Date(member.joinedAt.toNumber() * 1000),
  }
}

// ── Strategy Vault SDK methods ────────────────────────────────────────────────

export interface StrategyVaultDisplay {
  pubkey: string
  name: string
  description: string
  creator: string
  entryFeeLamports: number
  entryFeeSol: number
  performanceFeeBps: number
  managementFeeBps: number
  referralBps: number
  participantCount: number
  tamagotchiLevel: number
  tamagotchiEmoji: string
  strategyType: string
  riskLevel: string
  isPublic: boolean
  createdAt: Date
}

export interface CreateStrategyVaultParams {
  potName: string
  description: string
  entryFeeLamports: number
  performanceFeeBps: number   // 0–10000 (100 bps = 1%)
  managementFeeBps: number    // 0–10000
  referralBps: number         // 0–5000
  strategyType: 'DCA' | 'Trend' | 'Reversion' | 'Yield' | 'Custom'
  riskLevel: 'Conservative' | 'Balanced' | 'Aggressive'
  maxDrawdownBps: number      // max acceptable drawdown
  targetApyBps: number        // target APY in bps
}

/**
 * Build the instruction to create a Strategy Vault.
 * Caller must sign and send the returned transaction.
 */
export async function buildCreateStrategyVaultTx(
  program: Program<any>,
  authority: PublicKey,
  params: CreateStrategyVaultParams,
): Promise<Transaction> {
  const strategyConfig = {
    strategyType:   { [params.strategyType.toLowerCase()]: {} },
    riskLevel:      { [params.riskLevel.toLowerCase()]: {} },
    maxDrawdownBps: params.maxDrawdownBps,
    targetApyBps:   params.targetApyBps,
    rebalanceFrequencyHours: 24,
  }

  const tx = await (program as any).methods
    .createStrategyVault(
      params.potName,
      params.description,
      new BN(params.entryFeeLamports),
      params.performanceFeeBps,
      params.managementFeeBps,
      params.referralBps,
      strategyConfig,
    )
    .accounts({ authority })
    .transaction()

  return tx
}

export interface JoinStrategyVaultParams {
  vaultPubkey: PublicKey
  participant: PublicKey
  referrerWallet?: PublicKey
}

/**
 * Build the instruction to join a Strategy Vault.
 * Pays the entry fee set by the vault creator.
 */
export async function buildJoinStrategyVaultTx(
  program: Program<any>,
  params: JoinStrategyVaultParams,
): Promise<Transaction> {
  const tx = await (program as any).methods
    .joinStrategyVault(params.referrerWallet ?? null)
    .accounts({
      strategyVault: params.vaultPubkey,
      participant:   params.participant,
      systemProgram: SystemProgram.programId,
    })
    .transaction()

  return tx
}

export interface ExitStrategyVaultParams {
  vaultPubkey: PublicKey
  participant: PublicKey
  profitLamports: number   // on-chain profit for fee calculation
}

/**
 * Build the instruction to exit a Strategy Vault.
 * Performance fee on profit is deducted automatically.
 */
export async function buildExitStrategyVaultTx(
  program: Program<any>,
  params: ExitStrategyVaultParams,
): Promise<Transaction> {
  const tx = await (program as any).methods
    .exitStrategyVault(new BN(params.profitLamports))
    .accounts({
      strategyVault: params.vaultPubkey,
      participant:   params.participant,
    })
    .transaction()

  return tx
}

/**
 * Build the instruction to evolve the vault Tamagotchi.
 * Permissionless — anyone can call (no signing required).
 */
export async function buildEvolveTamagotchiTx(
  program: Program<any>,
  vaultPubkey: PublicKey,
): Promise<Transaction> {
  const tx = await (program as any).methods
    .evolveTamagotchi()
    .accounts({ strategyVault: vaultPubkey })
    .transaction()

  return tx
}

/**
 * Fetch all Strategy Vault accounts from the program.
 * Filters by discriminator to avoid loading regular POT accounts.
 */
export async function fetchAllStrategyVaults(
  connection: Connection,
  programId = POT_PROGRAM_ID,
) {
  // StrategyVaultAccount discriminator (first 8 bytes of SHA256("account:StrategyVaultAccount"))
  // Will be auto-computed by Anchor — for now use dataSize filter
  const accounts = await connection.getProgramAccounts(programId, {
    filters: [
      { dataSize: 8 + 300 }, // approximate StrategyVaultAccount size
    ],
  })
  return accounts
}

// ── Oracle / NAV (Phase A) helpers ───────────────────────────────────────────
//
// On-chain the program reads Pyth with a confidence bound + a swap deviation
// guard. Off-chain the UI prices NAV from the Pyth Price API (Hermes) — the
// same source, no manual price entry anywhere. NAV counts idle SOL PLUS every
// token leg the vault holds, fixing the SOL-only under-reporting of the old
// share_price.

/** One priced holding for NAV: a token amount and its USD price. */
export interface NavHolding {
  /** UI amount (already scaled out of base units). */
  amount: number
  /** USD price per unit (from Pyth Price API). */
  priceUsd: number
}

export interface NavResult {
  navUsd: number
  navPerShareUsd: number
}

/**
 * Compute pot NAV and NAV/share from idle SOL + token holdings, all priced
 * via the Pyth Price API. `solPriceUsd` and each holding's `priceUsd` come
 * from `fetchPythPrices`. Mirrors the on-chain `nav_per_share` semantics
 * (seeds at 1.0 when there are no shares).
 */
export function computeNav(
  idleSol: number,
  solPriceUsd: number,
  holdings: NavHolding[],
  totalShares: number,
): NavResult {
  const navUsd =
    idleSol * solPriceUsd +
    holdings.reduce((acc, h) => acc + h.amount * h.priceUsd, 0)
  const navPerShareUsd = totalShares > 0 ? navUsd / totalShares : solPriceUsd
  return { navUsd, navPerShareUsd }
}

/**
 * Fetch USD prices for a set of Pyth price-feed ids from the Hermes API.
 * Returns a map feedId → priceUsd. Network failures resolve to an empty map
 * so callers can render a graceful "—" rather than throw.
 */
export async function fetchPythPrices(
  feedIds: string[],
  hermesUrl = 'https://hermes.pyth.network',
): Promise<Record<string, number>> {
  if (feedIds.length === 0) return {}
  try {
    const qs = feedIds.map((id) => `ids[]=${id}`).join('&')
    const res = await fetch(`${hermesUrl}/v2/updates/price/latest?${qs}`)
    if (!res.ok) return {}
    const json = (await res.json()) as any
    const out: Record<string, number> = {}
    for (const p of json.parsed ?? []) {
      // price.price is an integer mantissa; expo is negative (e.g. -8).
      const px = Number(p.price.price) * Math.pow(10, p.price.expo)
      out[p.id] = px
    }
    return out
  } catch {
    return {}
  }
}

/** Configure the pot's oracle source + confidence/deviation guards (authority). */
export async function buildSetOracleConfigTx(
  program: Program<any>,
  pot: PublicKey,
  authority: PublicKey,
  opts: { oracleKind?: number; maxOracleConfBps?: number; maxOracleDeviationBps?: number },
): Promise<Transaction> {
  return await (program as any).methods
    .setOracleConfig({
      oracleKind: opts.oracleKind ?? 0,
      maxOracleConfBps: opts.maxOracleConfBps ?? 0,
      maxOracleDeviationBps: opts.maxOracleDeviationBps ?? 0,
    })
    .accounts({ pot, authority })
    .transaction()
}

// ── Security hardening (Phase A) helpers ─────────────────────────────────────
//
// Sentinel role, freeze/unfreeze, proposal cancellation, protocol allowlist
// and the risk-param timelock. The sentinel can stop things but can never
// move funds — there is no fund-moving instruction it is authorized for.

/** Assign or clear the pot's sentinel/guardian wallet (authority only). */
export async function buildSetSentinelTx(
  program: Program<any>,
  pot: PublicKey,
  authority: PublicKey,
  newSentinel: PublicKey | null,
): Promise<Transaction> {
  return await (program as any).methods
    .setSentinel(newSentinel)
    .accounts({ pot, authority })
    .transaction()
}

/** Freeze the pot — sentinel or authority. Blocks deposits, proposal
 *  execution, swaps and new strategies. Member withdrawals stay open. */
export async function buildFreezePotTx(
  program: Program<any>,
  pot: PublicKey,
  signer: PublicKey,
): Promise<Transaction> {
  return await (program as any).methods
    .freezePot()
    .accounts({ pot, signer })
    .transaction()
}

/** Unfreeze the pot — authority ONLY (the sentinel cannot self-serve). */
export async function buildUnfreezePotTx(
  program: Program<any>,
  pot: PublicKey,
  authority: PublicKey,
): Promise<Transaction> {
  return await (program as any).methods
    .unfreezePot()
    .accounts({ pot, signer: authority })
    .transaction()
}

/** Cancel an Active/Passed proposal — sentinel, authority or proposer. */
export async function buildCancelProposalTx(
  program: Program<any>,
  pot: PublicKey,
  proposal: PublicKey,
  signer: PublicKey,
): Promise<Transaction> {
  return await (program as any).methods
    .cancelProposal()
    .accounts({ pot, proposal, signer })
    .transaction()
}

/** Set the program-id allowlist for external CPI targets (max 8). */
export async function buildSetAllowedProgramsTx(
  program: Program<any>,
  pot: PublicKey,
  authority: PublicKey,
  programs: PublicKey[],
): Promise<Transaction> {
  return await (program as any).methods
    .setAllowedPrograms({ programs })
    .accounts({ pot, authority })
    .transaction()
}

/** Configure the risk-param timelock + per-asset exposure cap.
 *  Tightening applies instantly; loosening waits out the current timelock. */
export async function buildSetRiskTimelockTx(
  program: Program<any>,
  pot: PublicKey,
  authority: PublicKey,
  riskParamTimelockSecs: number,
  maxAssetExposureBps: number,
): Promise<Transaction> {
  return await (program as any).methods
    .setRiskTimelock({
      riskParamTimelockSecs: new BN(riskParamTimelockSecs),
      maxAssetExposureBps,
    })
    .accounts({ pot, authority })
    .transaction()
}

/** Permissionless crank: apply a staged risky-param change after its delay. */
export async function buildApplyPendingParamsTx(
  program: Program<any>,
  pot: PublicKey,
  cranker: PublicKey,
): Promise<Transaction> {
  return await (program as any).methods
    .applyPendingParams()
    .accounts({ pot, cranker })
    .transaction()
}

// ── Analytics helpers ─────────────────────────────────────────────────────────

export interface VaultAnalytics {
  pubkey: string
  navSol: number
  navUsd: number
  solPrice: number
  pnl30dPct: number
  apyPct: number
  winRate: number
  sharpeRatio: number
  tradeCount: number
  memberCount: number
  computedAt: Date
}

/**
 * Fetch vault analytics from the Next.js API route.
 * Works in both demo and production mode.
 */
export async function getVaultAnalytics(
  apiBaseUrl: string,
  vaultPubkey: string,
): Promise<VaultAnalytics | null> {
  try {
    const res = await fetch(`${apiBaseUrl}/api/vaults/${vaultPubkey}/analytics`)
    if (!res.ok) return null
    const json = await res.json() as any
    return {
      pubkey:       json.pubkey,
      navSol:       json.nav_sol,
      navUsd:       json.nav_usd,
      solPrice:     json.sol_price,
      pnl30dPct:    json.pnl_30d_pct,
      apyPct:       json.apy_pct,
      winRate:      json.win_rate,
      sharpeRatio:  json.sharpe_ratio,
      tradeCount:   json.trade_count,
      memberCount:  json.member_count,
      computedAt:   new Date(json.computed_at),
    }
  } catch {
    return null
  }
}
