import { AnchorProvider, Program, setProvider } from '@coral-xyz/anchor'
import { Connection, PublicKey, Commitment, LAMPORTS_PER_SOL } from '@solana/web3.js'
import { POT_PROGRAM_ID } from './pda.js'
import type { PotState, MemberState, ProposalState, PotDisplay, MemberDisplay } from './types.js'

export interface PotSDKConfig {
  rpcUrl: string
  commitment?: Commitment
  programId?: PublicKey
}

export function createConnection(rpcUrl: string, commitment: Commitment = 'confirmed') {
  return new Connection(rpcUrl, commitment)
}

/**
 * Returns an Anchor Program instance for the POT vault.
 * IDL is auto-generated by `anchor build`
 */
export function getPotProgram(provider: AnchorProvider, idl: any) {
  setProvider(provider)
  return new Program(idl as any, provider)
}

/**
 * Fetch all POT accounts from the program
 */
export async function fetchAllPots(connection: Connection, programId = POT_PROGRAM_ID) {
  const accounts = await connection.getProgramAccounts(programId, {
    filters: [
      { dataSize: 8 + 500 }, // Approximate PotAccount size — adjust after IDL build
    ],
  })
  return accounts
}

/**
 * Fetch all POTs a wallet belongs to (via member PDAs)
 */
export async function fetchUserPots(connection: Connection, wallet: PublicKey, programId = POT_PROGRAM_ID) {
  const accounts = await connection.getProgramAccounts(programId, {
    filters: [
      { memcmp: { offset: 8, bytes: wallet.toBase58() } },
    ],
  })
  return accounts
}

/**
 * Convert on-chain PotState + vault balance to display-friendly format
 */
export function potToDisplay(pubkey: PublicKey, pot: PotState, vaultBalance: number): PotDisplay {
  const TAMA_EMOJIS = ['\ud83e\udd5a', '\ud83d\udc23', '\ud83d\udc24', '\ud83e\udd85', '\ud83d\udc09', '\ud83d\udc51']
  const strategyKey = Object.keys(pot.config.yieldStrategy)[0]

  return {
    pubkey: pubkey.toBase58(),
    name: pot.name,
    emoji: pot.emoji || '\ud83e\udeb4',
    balance: vaultBalance / LAMPORTS_PER_SOL,
    totalShares: pot.totalShares.toNumber(),
    memberCount: pot.memberCount,
    tradeCount: pot.tradeCount,
    tamagotchiLevel: pot.tamagotchiLevel,
    tamagotchiEmoji: TAMA_EMOJIS[pot.tamagotchiLevel] || '\ud83e\udd5a',
    yieldStrategy: strategyKey,
    governanceLevel: pot.governance.tradeLevel,
    isPublic: pot.config.isPublic,
    createdAt: new Date(pot.createdAt.toNumber() * 1000),
  }
}

/**
 * Convert on-chain MemberState to display-friendly format
 */
export function memberToDisplay(member: MemberState, totalShares: number): MemberDisplay {
  const shares = member.shares.toNumber()
  return {
    wallet: member.wallet.toBase58(),
    shares,
    sharePercent: totalShares > 0 ? (shares / totalShares) * 100 : 0,
    depositTotal: member.depositTotal.toNumber() / LAMPORTS_PER_SOL,
    withdrawTotal: member.withdrawTotal.toNumber() / LAMPORTS_PER_SOL,
    pnl: (member.withdrawTotal.toNumber() - member.depositTotal.toNumber()) / LAMPORTS_PER_SOL,
    joinedAt: new Date(member.joinedAt.toNumber() * 1000),
  }
}
