/**
 * Asset registry for the web app. On devnet this is generated by scripts/pot-index-devnet-init.ts
 * (test mints with real Pyth feeds). On mainnet it will list real mints.
 */
import devnet from './assets.devnet.json'
import type { AssetInfo } from './client'

const cluster = (process.env.NEXT_PUBLIC_SOLANA_NETWORK ?? 'devnet').toLowerCase()

interface Registry {
  cluster: string
  programId: string
  usdcMint: string
  treasury: string
  flagship: string | null
  assets: Record<string, AssetInfo>
}

const REGISTRY: Registry = devnet as Registry

export const POT_INDEX_SETTINGS = {
  cluster,
  programId: REGISTRY.programId,
  usdcMint: REGISTRY.usdcMint,
  treasury: REGISTRY.treasury,
  flagship: REGISTRY.flagship,
  explorerCluster: cluster === 'mainnet-beta' || cluster === 'mainnet' ? '' : `?cluster=${cluster}`,
}

export const POT_INDEX_ASSETS: AssetInfo[] = Object.values(REGISTRY.assets)

export function assetByMint(mint: string): AssetInfo | undefined {
  return POT_INDEX_ASSETS.find((a) => a.mint === mint)
}

export function explorerAddress(addr: string): string {
  return `https://explorer.solana.com/address/${addr}${POT_INDEX_SETTINGS.explorerCluster}`
}
export function explorerTx(sig: string): string {
  return `https://explorer.solana.com/tx/${sig}${POT_INDEX_SETTINGS.explorerCluster}`
}
