[features]
seeds = false
skip-lint = false

[programs.localnet]
pot_vault = "ED4zhABMV97obJSD5bzasUPaNVmc3qwA3WhwqoGVCDvH"

[programs.devnet]
pot_vault = "ED4zhABMV97obJSD5bzasUPaNVmc3qwA3WhwqoGVCDvH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/pot_vault",
]
