#!/usr/bin/env bash
# =============================================================================
# PotBot v2 — Devnet Deploy Script
# =============================================================================
# Requirements:
#   - Rust:    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#   - Solana:  sh -c "$(curl -sSfL https://release.solana.com/v1.18.0/install)"
#   - Anchor:  cargo install --git https://github.com/coral-xyz/anchor avm --locked
#              avm install 0.30.1 && avm use 0.30.1
# =============================================================================
set -e

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${BLUE}[deploy]${NC} $1"; }
ok()   { echo -e "${GREEN}[ok]${NC}    $1"; }
warn() { echo -e "${YELLOW}[warn]${NC}  $1"; }
err()  { echo -e "${RED}[error]${NC} $1"; exit 1; }

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# ──────────────────────────────────────────────────────────────────────────────
# 1. Check prerequisites
# ──────────────────────────────────────────────────────────────────────────────
log "Checking prerequisites..."
command -v solana  &>/dev/null || err "Solana CLI not found. Install: sh -c \"\$(curl -sSfL https://release.solana.com/v1.18.0/install)\""
command -v anchor  &>/dev/null || err "Anchor CLI not found. Install: cargo install --git https://github.com/coral-xyz/anchor avm --locked"
command -v cargo   &>/dev/null || err "Rust/Cargo not found. Install: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
ok "All prerequisites found"

# ──────────────────────────────────────────────────────────────────────────────
# 2. Configure Solana CLI for devnet
# ──────────────────────────────────────────────────────────────────────────────
log "Configuring Solana CLI for devnet..."
solana config set --url https://api.devnet.solana.com

# Check keypair
if [ ! -f ~/.config/solana/id.json ]; then
  warn "No keypair found at ~/.config/solana/id.json"
  log "Generating new keypair..."
  solana-keygen new --outfile ~/.config/solana/id.json --no-bip39-passphrase
fi

DEPLOYER=$(solana address)
log "Deployer wallet: $DEPLOYER"

# ──────────────────────────────────────────────────────────────────────────────
# 3. Airdrop SOL if needed (devnet)
# ──────────────────────────────────────────────────────────────────────────────
BALANCE=$(solana balance --url devnet | awk '{print $1}' | cut -d. -f1)
log "Current balance: ${BALANCE} SOL"

if [ "$BALANCE" -lt 3 ] 2>/dev/null; then
  log "Balance low, requesting airdrop..."
  solana airdrop 4 --url devnet || warn "Airdrop failed (rate limited). Try: https://faucet.solana.com"
  sleep 5
  solana balance --url devnet
fi

# ──────────────────────────────────────────────────────────────────────────────
# 4. Build
# ──────────────────────────────────────────────────────────────────────────────
log "Building Anchor program..."
anchor build
ok "Build successful"

# ──────────────────────────────────────────────────────────────────────────────
# 5. Check if program ID matches keypair (IMPORTANT)
# ──────────────────────────────────────────────────────────────────────────────
ACTUAL_ID=$(anchor keys list 2>/dev/null | grep pot_vault | awk '{print $2}' || true)
HARDCODED_ID="Hyi1PNxPMUqwdDukhB2a4fvcBxQHmbXy3CZ95mgyFHA3"

if [ -n "$ACTUAL_ID" ] && [ "$ACTUAL_ID" != "$HARDCODED_ID" ]; then
  warn "Program ID mismatch!"
  warn "  Keypair ID : $ACTUAL_ID"
  warn "  Hardcoded  : $HARDCODED_ID"
  warn "Updating declare_id! and Anchor.toml..."

  # Update lib.rs
  sed -i.bak "s/$HARDCODED_ID/$ACTUAL_ID/g" programs/pot_vault/src/lib.rs
  # Update Anchor.toml
  sed -i.bak "s/$HARDCODED_ID/$ACTUAL_ID/g" Anchor.toml

  log "Rebuilding with corrected program ID..."
  anchor build
  ok "Rebuild successful"

  PROGRAM_ID="$ACTUAL_ID"
else
  ok "Program ID matches: $HARDCODED_ID"
  PROGRAM_ID="$HARDCODED_ID"
fi

# ──────────────────────────────────────────────────────────────────────────────
# 6. Deploy
# ──────────────────────────────────────────────────────────────────────────────
log "Deploying to devnet..."
anchor deploy --provider.cluster devnet
ok "Program deployed!"

# ──────────────────────────────────────────────────────────────────────────────
# 7. Write frontend .env.local
# ──────────────────────────────────────────────────────────────────────────────
ENV_FILE="../../apps/web/.env.local"
log "Writing frontend env to $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Auto-generated by deploy.sh — $(date)
NEXT_PUBLIC_PROGRAM_ID=${PROGRAM_ID}
NEXT_PUBLIC_RPC_URL=https://api.devnet.solana.com
NEXT_PUBLIC_NETWORK=devnet
EOF

ok "Frontend env written"

# ──────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}=====================================================${NC}"
echo -e "${GREEN} PotBot deployed to devnet!${NC}"
echo -e "${GREEN}=====================================================${NC}"
echo ""
echo "  Program ID : $PROGRAM_ID"
echo "  Explorer   : https://explorer.solana.com/address/$PROGRAM_ID?cluster=devnet"
echo ""
echo "  Next steps:"
echo "    cd ../../apps/web && npm run dev"
echo "    Open http://localhost:3000"
echo ""
