'use client'

import { useCallback, useMemo } from 'react'
import { useConnection, useWallet, useAnchorWallet } from '@solana/wallet-adapter-react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { AnchorProvider, Program, BN } from '@coral-xyz/anchor'
import { PublicKey, LAMPORTS_PER_SOL, SystemProgram } from '@solana/web3.js'
import {
  getPotAddress,
  getVaultAddress,
  getMemberAddress,
  getProposalAddress,
  POT_PROGRAM_ID,
} from '@potbot/sdk'
import type { PotDisplay, MemberDisplay, ProposalDisplay } from '@potbot/sdk'

// IDL will be generated by `anchor build` — for now use a placeholder import
// import idl from '../../../../packages/program/target/idl/pot_vault.json'
// For demo, we pass IDL via context or fetch it

/* ── Provider Hook ── */

export function useProgram() {
  const { connection } = useConnection()
  const wallet = useAnchorWallet()

  return useMemo(() => {
    if (!wallet) return null
    const provider = new AnchorProvider(connection, wallet, {
      commitment: 'confirmed',
    })
    // Once IDL is available from anchor build, uncomment:
    // return new Program(idl as any, POT_PROGRAM_ID, provider)
    return { provider, programId: POT_PROGRAM_ID }
  }, [connection, wallet])
}

/* ── Fetch All POTs ── */

export function usePots() {
  const { connection } = useConnection()

  return useQuery({
    queryKey: ['pots'],
    queryFn: async (): Promise<PotDisplay[]> => {
      const accounts = await connection.getProgramAccounts(POT_PROGRAM_ID)

      // Parse accounts using Anchor deserialization
      // For now, return mock data for UI development
      return accounts.map((acc) => ({
        pubkey: acc.pubkey.toBase58(),
        name: 'Loading...',
        emoji: '\ud83e\udeb4',
        balance: 0,
        totalShares: 0,
        memberCount: 0,
        tradeCount: 0,
        tamagotchiLevel: 0,
        tamagotchiEmoji: '\ud83e\udd5a',
        yieldStrategy: 'none',
        governanceLevel: 2,
        isPublic: true,
        createdAt: new Date(),
      }))
    },
    staleTime: 10_000,
    retry: 2,
  })
}

/* ── Fetch Single POT ── */

export function usePot(pubkey: string | undefined) {
  const { connection } = useConnection()

  return useQuery({
    queryKey: ['pot', pubkey],
    queryFn: async () => {
      if (!pubkey) return null
      const pk = new PublicKey(pubkey)
      const [vaultPda] = getVaultAddress(pk)

      const [potInfo, vaultInfo] = await Promise.all([
        connection.getAccountInfo(pk),
        connection.getBalance(vaultPda),
      ])

      if (!potInfo) return null

      return {
        pubkey,
        vaultBalance: vaultInfo / LAMPORTS_PER_SOL,
        raw: potInfo,
      }
    },
    enabled: !!pubkey,
    staleTime: 5_000,
  })
}

/* ── Fetch Members ── */

export function useMembers(potPubkey: string | undefined) {
  const { connection } = useConnection()

  return useQuery({
    queryKey: ['members', potPubkey],
    queryFn: async (): Promise<MemberDisplay[]> => {
      if (!potPubkey) return []

      const accounts = await connection.getProgramAccounts(POT_PROGRAM_ID, {
        filters: [
          { memcmp: { offset: 8, bytes: potPubkey } },
        ],
      })

      return accounts.map((acc) => ({
        wallet: acc.pubkey.toBase58(),
        shares: 0,
        sharePercent: 0,
        depositTotal: 0,
        withdrawTotal: 0,
        pnl: 0,
        joinedAt: new Date(),
      }))
    },
    enabled: !!potPubkey,
    staleTime: 10_000,
  })
}

/* ── Fetch Proposals ── */

export function useProposals(potPubkey: string | undefined) {
  const { connection } = useConnection()

  return useQuery({
    queryKey: ['proposals', potPubkey],
    queryFn: async (): Promise<ProposalDisplay[]> => {
      if (!potPubkey) return []

      const accounts = await connection.getProgramAccounts(POT_PROGRAM_ID, {
        filters: [
          { memcmp: { offset: 8, bytes: potPubkey } },
        ],
      })

      return accounts.map((acc) => ({
        pubkey: acc.pubkey.toBase58(),
        proposalId: 0,
        proposer: '',
        type: 'swap',
        description: '',
        status: 'active',
        yesPercent: 0,
        noPercent: 0,
        createdAt: new Date(),
        resolvedAt: null,
      }))
    },
    enabled: !!potPubkey,
    staleTime: 5_000,
  })
}

/* ─────── MUTATIONS ─────── */

/* ── Create POT ── */

export function useCreatePot() {
  const { connection } = useConnection()
  const wallet = useAnchorWallet()
  const { publicKey, sendTransaction } = useWallet()
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async (params: {
      name: string
      emoji: string
      isPublic: boolean
      minDeposit: number
      lockupSeconds: number
      yieldStrategy: number
      tradeLevel: number
      withdrawLevel: number
    }) => {
      if (!wallet || !publicKey) throw new Error('Wallet not connected')

      const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })

      const [potPda] = getPotAddress(publicKey, params.name)
      const [vaultPda] = getVaultAddress(potPda)

      const tx = await provider.connection.getLatestBlockhash()

      return {
        potAddress: potPda.toBase58(),
        vaultAddress: vaultPda.toBase58(),
        message: `POT "${params.name}" PDA: ${potPda.toBase58()}`,
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pots'] })
    },
  })
}

/* ── Deposit ── */

export function useDeposit() {
  const { connection } = useConnection()
  const wallet = useAnchorWallet()
  const { publicKey } = useWallet()
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async (params: {
      potAddress: string
      amountSol: number
    }) => {
      if (!wallet || !publicKey) throw new Error('Wallet not connected')

      const potPk = new PublicKey(params.potAddress)
      const [memberPda] = getMemberAddress(potPk, publicKey)
      const [vaultPda] = getVaultAddress(potPk)
      const lamports = new BN(params.amountSol * LAMPORTS_PER_SOL)

      return {
        memberAddress: memberPda.toBase58(),
        vaultAddress: vaultPda.toBase58(),
        amount: params.amountSol,
      }
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({ queryKey: ['pot', vars.potAddress] })
      queryClient.invalidateQueries({ queryKey: ['members', vars.potAddress] })
    },
  })
}

/* ── Withdraw ── */

export function useWithdraw() {
  const { connection } = useConnection()
  const wallet = useAnchorWallet()
  const { publicKey } = useWallet()
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async (params: {
      potAddress: string
      shares: number
    }) => {
      if (!wallet || !publicKey) throw new Error('Wallet not connected')

      const potPk = new PublicKey(params.potAddress)
      const [memberPda] = getMemberAddress(potPk, publicKey)
      const [vaultPda] = getVaultAddress(potPk)

      return {
        memberAddress: memberPda.toBase58(),
        shares: params.shares,
      }
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({ queryKey: ['pot', vars.potAddress] })
      queryClient.invalidateQueries({ queryKey: ['members', vars.potAddress] })
    },
  })
}

/* ── Create Proposal ── */

export function useCreateProposal() {
  const { connection } = useConnection()
  const wallet = useAnchorWallet()
  const { publicKey } = useWallet()
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async (params: {
      potAddress: string
      nextProposalId: number
      proposalType: any
      description: string
    }) => {
      if (!wallet || !publicKey) throw new Error('Wallet not connected')

      const potPk = new PublicKey(params.potAddress)
      const [proposalPda] = getProposalAddress(potPk, params.nextProposalId)
      const [memberPda] = getMemberAddress(potPk, publicKey)

      return {
        proposalAddress: proposalPda.toBase58(),
        proposalId: params.nextProposalId,
      }
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({ queryKey: ['proposals', vars.potAddress] })
      queryClient.invalidateQueries({ queryKey: ['pot', vars.potAddress] })
    },
  })
}

/* ── Vote ── */

export function useVote() {
  const { connection } = useConnection()
  const wallet = useAnchorWallet()
  const { publicKey } = useWallet()
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async (params: {
      potAddress: string
      proposalAddress: string
      approve: boolean
    }) => {
      if (!wallet || !publicKey) throw new Error('Wallet not connected')

      const potPk = new PublicKey(params.potAddress)
      const [memberPda] = getMemberAddress(potPk, publicKey)

      return {
        vote: params.approve ? 'YES' : 'NO',
      }
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({ queryKey: ['proposals', vars.potAddress] })
    },
  })
}

/* ── Execute Proposal ── */

export function useExecuteProposal() {
  const { connection } = useConnection()
  const wallet = useAnchorWallet()
  const { publicKey } = useWallet()
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async (params: {
      potAddress: string
      proposalAddress: string
    }) => {
      if (!wallet || !publicKey) throw new Error('Wallet not connected')

      const potPk = new PublicKey(params.potAddress)
      const [vaultPda] = getVaultAddress(potPk)

      return { executed: true }
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({ queryKey: ['pot', vars.potAddress] })
      queryClient.invalidateQueries({ queryKey: ['proposals', vars.potAddress] })
    },
  })
}
